//! UI routes for API documentation.
//!
//! This module provides alternative API documentation UIs
//! for the OpenAPI specification generated by utoipa.

use axum::Router;
use utoipa::OpenApi;
use utoipa_swagger_ui::SwaggerUi;

use super::ApiDoc;

/// Creates a router that serves Swagger UI at `/docs/swagger`.
///
/// This function returns an Axum router configured to serve the interactive
/// Swagger UI documentation interface. The Swagger UI will load the OpenAPI
/// specification from `/docs/openapi.json`.
///
/// # Route
///
/// - `GET /docs/swagger` - Swagger UI HTML interface
/// - `GET /docs/openapi.json` - OpenAPI specification (auto-generated)
///
/// # Example
///
/// ```rust,no_run
/// use axum::Router;
/// use crate::docs::ui::swagger;
///
/// let app = Router::new().merge(swagger());
/// ```
pub fn swagger() -> Router {
	SwaggerUi::new("/docs/swagger")
		.url("/docs/openapi.json", ApiDoc::openapi())
		.into()
}

/// Creates a router that serves Scalar UI at `/docs/scalar`.
///
/// This function returns an Axum router that provides Scalar UI
/// for viewing and interacting with the OpenAPI specification.
///
/// # Feature Flag
/// This function is only available when the `scalar-ui` feature is enabled.
///
/// # Route
/// Serves Scalar UI at `/docs/scalar` using the OpenAPI spec from `ApiDoc`.
#[cfg(feature = "scalar-ui")]
pub fn scalar() -> Router {
	use utoipa_scalar::Scalar;
	use utoipa_scalar::Servable;
	Scalar::with_url("/docs/scalar", ApiDoc::openapi()).into()
}
