name: altair_core
description: Core business logic, models, and data layer for Altair applications
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Database
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2
  path: ^1.8.3
  path_provider: ^2.1.2

  # Shared database service
  altair_db_service:
    path: ../altair-db-service

  # JSON serialization
  json_annotation: ^4.8.1

  # Utilities
  uuid: ^4.3.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
