name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us resolve the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Flutter App (altair_guidance)
        - Backend Service (auth-service)
        - Core Package (altair-core)
        - Auth Package (altair-auth)
        - UI Package (altair-ui)
        - CI/CD
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform(s) are affected?
      multiple: true
      options:
        - Linux
        - Android
        - iOS
        - Web
        - Windows
        - macOS
        - All platforms
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Provide relevant environment information
      placeholder: |
        - OS: [e.g., Ubuntu 22.04]
        - Flutter version: [e.g., 3.24.0]
        - Python version: [e.g., 3.12]
        - Browser (if applicable): [e.g., Chrome 120]
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs/Stack Trace
      description: If applicable, paste relevant logs or stack traces
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
    validations:
      required: false
