blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/getaltair/altair/discussions
    about: Ask questions or discuss ideas with the community
  - name: Documentation
    url: https://github.com/getaltair/altair/blob/main/README.md
    about: Check the documentation for guides and reference materials
