name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I also considered...
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Flutter App (altair_guidance)
        - Backend Service (auth-service)
        - Core Package (altair-core)
        - Auth Package (altair-auth)
        - UI Package (altair-ui)
        - CI/CD
        - Documentation
        - Infrastructure
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Important for my workflow
        - Medium - Would be nice to have
        - Low - Minor improvement
    validations:
      required: true

  - type: checkboxes
    id: user-type
    attributes:
      label: User Type
      description: Who would benefit from this feature?
      options:
        - label: End users (people using the app)
        - label: Developers (people contributing to the project)
        - label: Both

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. As a user, I want to...
        2. This would help when...
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, wireframes, or examples from other apps
    validations:
      required: false

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Considerations
      description: Any technical details or implementation suggestions?
      placeholder: This might require changes to...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the feature request here
    validations:
      required: false

  - type: checkboxes
    id: willing-to-implement
    attributes:
      label: Implementation
      description: Are you willing to help implement this feature?
      options:
        - label: I am willing to submit a PR for this feature
