name: altair_auth
description: Authentication and authorization package for Altair ecosystem
version: 0.1.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP client
  dio: ^5.4.0

  # Secure storage
  flutter_secure_storage: ^9.2.4

  # State management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # JWT handling
  jwt_decode: ^0.3.1

  # JSON serialization
  json_annotation: ^4.8.1

  # Logging
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generation
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

  # Testing
  mockito: ^5.4.4
  bloc_test: ^10.0.0
