/**
 * @altair/bindings
 *
 * Generated TypeScript bindings for Tauri IPC commands.
 *
 * This file exports placeholder types until tauri-specta generates the actual bindings.
 * Once Phase 4 is complete, this file will re-export from ./generated.ts which is
 * auto-generated from Rust command definitions.
 *
 * @see README.md for generation instructions
 */

// ============================================================================
// Placeholder Types (replaced by tauri-specta generated types in Phase 4)
// ============================================================================

/**
 * Placeholder for invoke function type.
 * Real version will be generated by tauri-specta with type-safe command names.
 */
export type InvokeFunction = <T>(cmd: string, args?: Record<string, unknown>) => Promise<T>;

/**
 * Placeholder command names type.
 * Real version lists all available Tauri commands.
 */
export type CommandName = string;

// ============================================================================
// Domain Types (will be generated from Rust types)
// ============================================================================

/** Energy cost for quests (ADHD-friendly task sizing) */
export type EnergyCost = 'low' | 'medium' | 'high' | 'epic';

/** Status for all entities */
export type EntityStatus = 'active' | 'archived';

/** Base entity fields present on all domain types */
export interface BaseEntity {
  id: string;
  owner: string;
  createdAt: string;
  updatedAt: string;
  status: EntityStatus;
}

// ============================================================================
// Guidance App Types
// ============================================================================

export interface Quest extends BaseEntity {
  title: string;
  description?: string;
  energyCost: EnergyCost;
  campaignId?: string;
  dueDate?: string;
  completedAt?: string;
}

export interface Campaign extends BaseEntity {
  title: string;
  description?: string;
}

// ============================================================================
// Knowledge App Types
// ============================================================================

export interface Note extends BaseEntity {
  title: string;
  content: string;
  folderId?: string;
  tags: string[];
}

export interface Folder extends BaseEntity {
  name: string;
  parentId?: string;
}

// ============================================================================
// Tracking App Types
// ============================================================================

export interface Item extends BaseEntity {
  name: string;
  description?: string;
  quantity: number;
  locationId?: string;
  imageUrl?: string;
}

export interface Location extends BaseEntity {
  name: string;
  description?: string;
  parentId?: string;
}

// ============================================================================
// Quick Capture Types
// ============================================================================

export type CaptureType = 'quest' | 'note' | 'item' | 'unknown';

export interface Capture extends BaseEntity {
  content: string;
  captureType: CaptureType;
  processedAt?: string;
  targetId?: string;
}

// ============================================================================
// Generated Bindings (auto-generated by tauri-specta)
// ============================================================================

/**
 * Each app generates its own bindings file during build.
 * Import commands from specific app modules as needed:
 *
 * import * as guidanceCommands from '@altair/bindings/guidance';
 * import * as knowledgeCommands from '@altair/bindings/knowledge';
 * import * as trackingCommands from '@altair/bindings/tracking';
 * import * as mobileCommands from '@altair/bindings/mobile';
 */

// Re-export generated bindings from each app
export * as guidance from './guidance';
export * as knowledge from './knowledge';
export * as tracking from './tracking';
export * as mobile from './mobile';
