// Shared types re-exported for convenience
// These types are common across multiple apps and can be imported directly

/**
 * Once domain types are generated by tauri-specta, uncomment these exports:
 *
 * export type {
 *   EntityStatus,
 *   EnergyCost,
 *   UserRole,
 *   User,
 *   UserPreferences,
 *   Attachment,
 *   Tag,
 *   Capture,
 *   CaptureStatus,
 *   CaptureType,
 *   CaptureSource,
 * } from './guidance';
 *
 * export type { Result } from './guidance';
 */

// Temporary placeholder until domain types are generated
// The Tauri apps need to run in debug mode to export types via tauri-specta
export type Placeholder = {
  message: string;
};
