"""Add username and adhd_profile to users

Revision ID: 52835f621260
Revises: 23debc2d9145
Create Date: 2025-10-04 17:52:37.795822

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52835f621260"
down_revision: Union[str, Sequence[str], None] = "23debc2d9145"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(length=50), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "adhd_profile", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_column("users", "adhd_profile")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
