name: altair-guidance
version: '0.1.0'
summary: ADHD-friendly task and project management
description: |
  Altair Guidance is a powerful task and project management application
  designed specifically for people with ADHD. Features include:

  - Quick task capture (< 3 seconds)
  - AI-powered task breakdown
  - Smart prioritization
  - Time tracking with visual feedback
  - Focus mode to minimize distractions
  - Keyboard shortcuts for power users
  - 100% offline-first operation

  Part of the Altair ecosystem for ADHD-friendly productivity.

grade: stable
confinement: strict
base: core22
architectures:
  - build-on: amd64

apps:
  altair-guidance:
    command: altair_guidance
    extensions: [gnome]
    plugs:
      - home
      - network
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - audio-playback

parts:
  altair-guidance:
    plugin: flutter
    source: ../..
    flutter-target: lib/main.dart
    build-packages:
      - clang
      - cmake
      - ninja-build
      - libgtk-3-dev
      - libsecret-1-dev
      - libjsoncpp-dev
    stage-packages:
      - libgtk-3-0
      - libsecret-1-0
      - libjsoncpp25
