-- Down migration for 20260412000005
ALTER TABLE users DROP COLUMN IF EXISTS status;
ALTER TABLE users DROP COLUMN IF EXISTS is_admin;
ALTER TABLE users DROP COLUMN IF EXISTS password_hash;
ALTER TABLE users ADD COLUMN oidc_sub TEXT NOT NULL DEFAULT '' UNIQUE;
