package com.getaltair.altair.ui.theme

import androidx.compose.ui.graphics.Color

// ── Ethereal Canvas design tokens ──────────────────────────────────────────

val FoggyCanvasWhite = Color(0xFFF8FAFA)
val GossamerWhite = Color(0xFFFFFFFF)
val PaleSeafoamMist = Color(0xFFF0F4F5)
val DeepMutedTealNavy = Color(0xFF446273)
val SkyWashedAqua = Color(0xFFC7E7FA)
val MidnightCharcoal = Color(0xFF2A3435)
val SophisticatedTerracotta = Color(0xFF9F403D)
val WeatheredSlate = Color(0xFF41545A)
val GhostBorderAsh = Color(0xFFC0D4DA)
val SoftSlateHaze = Color(0xFFDCE5E8)

// ── Extended palette for Material 3 roles ─────────────────────────────────

val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFC7E7FA)
val OnPrimaryContainerLight = Color(0xFF002C3D)
val SecondaryLight = Color(0xFF5A7A8A)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFCCE8F4)
val OnSecondaryContainerLight = Color(0xFF101F26)
val TertiaryLight = Color(0xFF7D5248)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFFFDAD4)
val OnTertiaryContainerLight = Color(0xFF311009)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val SurfaceVariantLight = Color(0xFFDCE5E8)
val OnSurfaceVariantLight = Color(0xFF41545A)
val OutlineLight = Color(0xFF71898F)
val OutlineVariantLight = Color(0xFFC0D4DA)
val ScrimColor = Color(0xFF1A1C1E)
val InverseSurfaceLight = Color(0xFF2E3A3C)
val InverseOnSurfaceLight = Color(0xFFECF2F3)
val InversePrimaryLight = Color(0xFF8DCDE8)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFF0F4F5)
val SurfaceContainerLight2 = Color(0xFFE4EEF1)
val SurfaceContainerHighLight = Color(0xFFDEE8EB)
val SurfaceContainerHighestLight = Color(0xFFD8E2E5)

// ── Dark theme ─────────────────────────────────────────────────────────────

val PrimaryDark = Color(0xFF8DCDE8)
val OnPrimaryDark = Color(0xFF002C3D)
val PrimaryContainerDark = Color(0xFF1D4A5E)
val OnPrimaryContainerDark = Color(0xFFC7E7FA)
val SecondaryDark = Color(0xFFAACFE0)
val OnSecondaryDark = Color(0xFF1A3840)
val SecondaryContainerDark = Color(0xFF2D4F5C)
val OnSecondaryContainerDark = Color(0xFFCCE8F4)
val TertiaryDark = Color(0xFFFFB4A8)
val OnTertiaryDark = Color(0xFF4C1D16)
val TertiaryContainerDark = Color(0xFF6B3229)
val OnTertiaryContainerDark = Color(0xFFFFDAD4)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF0F1A1C)
val OnBackgroundDark = Color(0xFFDCE5E8)
val SurfaceDark = Color(0xFF0F1A1C)
val OnSurfaceDark = Color(0xFFDCE5E8)
val SurfaceVariantDark = Color(0xFF41545A)
val OnSurfaceVariantDark = Color(0xFFBFC8CB)
val OutlineDark = Color(0xFF8A9EA4)
val OutlineVariantDark = Color(0xFF41545A)
val InverseSurfaceDark = Color(0xFFDCE5E8)
val InverseOnSurfaceDark = Color(0xFF2E3A3C)
val InversePrimaryDark = Color(0xFF446273)
val SurfaceContainerLowestDark = Color(0xFF0A1214)
val SurfaceContainerLowDark = Color(0xFF1A2829)
val SurfaceContainerDark2 = Color(0xFF1E2D30)
val SurfaceContainerHighDark = Color(0xFF293536)
val SurfaceContainerHighestDark = Color(0xFF343F41)
