port: 8080

replication:
  connections:
    - type: postgresql
      uri: !env PS_DATABASE_URI
      sslmode: disable

storage:
  type: postgresql
  uri: !env PS_STORAGE_URI
  sslmode: disable

sync_config:
  path: /config/sync-rules.yaml

client_auth:
  jwks_uri: http://server:3000/api/auth/keys

api:
  tokens:
    - !env PS_ADMIN_TOKEN

migrations:
  disable_auto_migration: false
