name: Build

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build-linux:
    name: Build Linux App
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.6'
          channel: 'stable'
          cache: true

      - name: Install Linux dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            clang cmake ninja-build pkg-config libgtk-3-dev \
            liblzma-dev libstdc++-12-dev libsecret-1-dev

      - name: Get dependencies
        working-directory: apps/altair_guidance
        run: flutter pub get

      - name: Build Linux app
        working-directory: apps/altair_guidance
        run: flutter build linux --release

      - name: Archive build artifacts
        uses: actions/upload-artifact@v5
        with:
          name: linux-build
          path: apps/altair_guidance/build/linux/x64/release/bundle/
