name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint-python:
    name: Lint Python Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd services/auth-service
          uv sync --extra dev

      - name: Run Ruff linter
        run: |
          cd services/auth-service
          uv run ruff check .

      - name: Run Ruff formatter check
        run: |
          cd services/auth-service
          uv run ruff format --check .

      - name: Run mypy type checker
        run: |
          cd services/auth-service
          uv run mypy app/

  test-python:
    name: Test Python Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd services/auth-service
          uv sync --extra dev

      - name: Run tests
        run: |
          cd services/auth-service
          uv run pytest --cov=app --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          file: ./services/auth-service/coverage.xml
          flags: python
          name: auth-service

  lint-flutter:
    name: Lint Flutter Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies (altair-core)
        run: |
          cd packages/altair-core
          flutter pub get

      - name: Analyze altair-core
        run: |
          cd packages/altair-core
          flutter analyze

      - name: Install dependencies (altair-auth)
        run: |
          cd packages/altair-auth
          flutter pub get

      - name: Analyze altair-auth
        run: |
          cd packages/altair-auth
          flutter analyze

      - name: Install dependencies (altair-ui)
        run: |
          cd packages/altair-ui
          flutter pub get

      - name: Analyze altair-ui
        run: |
          cd packages/altair-ui
          flutter analyze

      - name: Install dependencies (altair-guidance)
        run: |
          cd apps/altair_guidance
          flutter pub get

      - name: Analyze altair-guidance
        run: |
          cd apps/altair_guidance
          flutter analyze

  test-flutter:
    name: Test Flutter Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Test altair-core
        run: |
          cd packages/altair-core
          flutter pub get
          flutter test --coverage

      - name: Test altair-auth
        run: |
          cd packages/altair-auth
          flutter pub get
          flutter test --coverage

      - name: Test altair-ui
        run: |
          cd packages/altair-ui
          flutter pub get
          flutter test --coverage

      - name: Test altair-guidance
        run: |
          cd apps/altair_guidance
          flutter pub get
          flutter test --coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          files: |
            ./packages/altair-core/coverage/lcov.info
            ./packages/altair-auth/coverage/lcov.info
            ./packages/altair-ui/coverage/lcov.info
            ./apps/altair_guidance/coverage/lcov.info
          flags: flutter
          name: flutter-packages

  # Build jobs disabled temporarily to save CI time and costs
  # Re-enable when ready for deployment
  # build-linux:
  #   name: Build Linux App
  #   runs-on: ubuntu-latest
  #   needs: [lint-flutter, test-flutter]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v5
  #
  #     - name: Install Linux dependencies
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y \
  #           clang cmake ninja-build pkg-config \
  #           libgtk-3-dev liblzma-dev libstdc++-12-dev \
  #           libsecret-1-dev
  #
  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: 'stable'
  #
  #     - name: Enable Linux desktop
  #       run: flutter config --enable-linux-desktop
  #
  #     - name: Install dependencies
  #       run: |
  #         cd apps/altair_guidance
  #         flutter pub get
  #
  #     - name: Build Linux app
  #       run: |
  #         cd apps/altair_guidance
  #         flutter build linux --release
  #
  #     - name: Upload Linux artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: altair-guidance-linux
  #         path: apps/altair_guidance/build/linux/x64/release/bundle/
  #
  # build-android:
  #   name: Build Android App
  #   runs-on: ubuntu-latest
  #   needs: [lint-flutter, test-flutter]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v5
  #
  #     - name: Set up Java
  #       uses: actions/setup-java@v4
  #       with:
  #         distribution: 'temurin'
  #         java-version: '17'
  #
  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: 'stable'
  #
  #     - name: Install dependencies
  #       run: |
  #         cd apps/altair_guidance
  #         flutter pub get
  #
  #     - name: Build Android APK
  #       run: |
  #         cd apps/altair_guidance
  #         flutter build apk --release
  #
  #     - name: Upload Android artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: altair-guidance-android
  #         path: apps/altair_guidance/build/app/outputs/flutter-apk/app-release.apk
