name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  lint-flutter:
    name: Lint Flutter Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Flutter
        uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e # v2
        with:
          flutter-version: '3.35.6'
          channel: 'stable'
          cache: true

      - name: Install dependencies (altair-core)
        run: |
          cd packages/altair-core
          flutter pub get

      - name: Analyze altair-core
        run: |
          cd packages/altair-core
          flutter analyze

      - name: Install dependencies (altair-auth)
        run: |
          cd packages/altair-auth
          flutter pub get

      - name: Analyze altair-auth
        run: |
          cd packages/altair-auth
          flutter analyze

      - name: Install dependencies (altair-ui)
        run: |
          cd packages/altair-ui
          flutter pub get

      - name: Analyze altair-ui
        run: |
          cd packages/altair-ui
          flutter analyze

      - name: Install dependencies (altair-guidance)
        run: |
          cd apps/altair_guidance
          flutter pub get

      - name: Analyze altair-guidance
        run: |
          cd apps/altair_guidance
          flutter analyze

  # Build jobs disabled temporarily to save CI time and costs
  # Re-enable when ready for deployment
  # build-linux:
  #   name: Build Linux App
  #   runs-on: ubuntu-latest
  #   needs: [lint-flutter, test-flutter]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v5
  #
  #     - name: Install Linux dependencies
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y \
  #           clang cmake ninja-build pkg-config \
  #           libgtk-3-dev liblzma-dev libstdc++-12-dev \
  #           libsecret-1-dev libfuse2
  #
  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: 'stable'
  #
  #     - name: Enable Linux desktop
  #       run: flutter config --enable-linux-desktop
  #
  #     - name: Install dependencies
  #       run: |
  #         cd apps/altair_guidance
  #         flutter pub get
  #
  #     - name: Build Linux app
  #       run: |
  #         cd apps/altair_guidance
  #         flutter build linux --release
  #
  #     - name: Upload Linux artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: altair-guidance-linux
  #         path: apps/altair_guidance/build/linux/x64/release/bundle/
  #
  # build-android:
  #   name: Build Android App
  #   runs-on: ubuntu-latest
  #   needs: [lint-flutter, test-flutter]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v5
  #
  #     - name: Set up Java
  #       uses: actions/setup-java@v4
  #       with:
  #         distribution: 'temurin'
  #         java-version: '17'
  #
  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: 'stable'
  #
  #     - name: Install dependencies
  #       run: |
  #         cd apps/altair_guidance
  #         flutter pub get
  #
  #     - name: Build Android APK
  #       run: |
  #         cd apps/altair_guidance
  #         flutter build apk --release
  #
  #     - name: Upload Android artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: altair-guidance-android
  #         path: apps/altair_guidance/build/app/outputs/flutter-apk/app-release.apk
